CELEBA_DATASET_DIRECTORY = "celeba"
CELEBA_IMAGE_DIRECTORY = "img_align_celeba"
SKETCH_IMAGE_DIRECTORY = "sketch_images"

FAIR_FACE_DATASET_DIRECTORY = "fairface-img-margin025-trainval"
FAIR_FACE_IMAGE_DIRECTORY = ["train", "val"]

UTK_FACE_DATASET_DIRECTORY = "UTKFace"
UTK_FACE_IMAGE_DIRECTORY = "UTKFace"

LFW_DATASET_DIRECTORY = "LFW"
LFW_IMAGE_DIRECTORY = "lfw-deepfunneled"

CELEBA_DATASET = "celeba"
FAIR_FACE_DATASET = "fair_face"
UTK_FACE_DATASET = "utk_face"
LFW_DATASET = "lfw"

BENCHMARK_NUM_EPOCHS = 100
BENCHMARK_NUM_EPOCHS_CELEBA = 50
BENCHMARK_EARLY_STOPPING_THRESHOLD = True
